// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// int_get_exif
List int_get_exif(std::string path);
RcppExport SEXP _exiv_int_get_exif(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(int_get_exif(path));
    return rcpp_result_gen;
END_RCPP
}
// int_set_exif_ascii
void int_set_exif_ascii(std::string path, std::string key, std::string value);
RcppExport SEXP _exiv_int_set_exif_ascii(SEXP pathSEXP, SEXP keySEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    int_set_exif_ascii(path, key, value);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_exiv_int_get_exif", (DL_FUNC) &_exiv_int_get_exif, 1},
    {"_exiv_int_set_exif_ascii", (DL_FUNC) &_exiv_int_set_exif_ascii, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_exiv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
