structure(list(key = c("Exif.Image.ProcessingSoftware", "Exif.Image.NewSubfileType",
"Exif.Image.SubfileType", "Exif.Image.ImageWidth", "Exif.Image.ImageLength",
"Exif.Image.BitsPerSample", "Exif.Image.Compression", "Exif.Image.PhotometricInterpretation",
"Exif.Image.Thresholding", "Exif.Image.CellWidth", "Exif.Image.CellLength",
"Exif.Image.FillOrder", "Exif.Image.DocumentName", "Exif.Image.ImageDescription",
"Exif.Image.Make", "Exif.Image.Model", "Exif.Image.StripOffsets",
"Exif.Image.Orientation", "Exif.Image.SamplesPerPixel", "Exif.Image.RowsPerStrip",
"Exif.Image.StripByteCounts", "Exif.Image.XResolution", "Exif.Image.YResolution",
"Exif.Image.PlanarConfiguration", "Exif.Image.GrayResponseUnit",
"Exif.Image.GrayResponseCurve", "Exif.Image.T4Options", "Exif.Image.T6Options",
"Exif.Image.ResolutionUnit", "Exif.Image.PageNumber", "Exif.Image.TransferFunction",
"Exif.Image.Software", "Exif.Image.DateTime", "Exif.Image.Artist",
"Exif.Image.HostComputer", "Exif.Image.Predictor", "Exif.Image.WhitePoint",
"Exif.Image.PrimaryChromaticities", "Exif.Image.ColorMap", "Exif.Image.HalftoneHints",
"Exif.Image.TileWidth", "Exif.Image.TileLength", "Exif.Image.TileOffsets",
"Exif.Image.TileByteCounts", "Exif.Image.SubIFDs", "Exif.Image.InkSet",
"Exif.Image.InkNames", "Exif.Image.NumberOfInks", "Exif.Image.DotRange",
"Exif.Image.TargetPrinter", "Exif.Image.ExtraSamples", "Exif.Image.SampleFormat",
"Exif.Image.SMinSampleValue", "Exif.Image.SMaxSampleValue", "Exif.Image.TransferRange",
"Exif.Image.ClipPath", "Exif.Image.XClipPathUnits", "Exif.Image.YClipPathUnits",
"Exif.Image.Indexed", "Exif.Image.JPEGTables", "Exif.Image.OPIProxy",
"Exif.Image.JPEGProc", "Exif.Image.JPEGInterchangeFormat", "Exif.Image.JPEGInterchangeFormatLength",
"Exif.Image.JPEGRestartInterval", "Exif.Image.JPEGLosslessPredictors",
"Exif.Image.JPEGPointTransforms", "Exif.Image.JPEGQTables", "Exif.Image.JPEGDCTables",
"Exif.Image.JPEGACTables", "Exif.Image.YCbCrCoefficients", "Exif.Image.YCbCrSubSampling",
"Exif.Image.YCbCrPositioning", "Exif.Image.ReferenceBlackWhite",
"Exif.Image.XMLPacket", "Exif.Image.Rating", "Exif.Image.RatingPercent",
"Exif.Image.ImageID", "Exif.Image.CFARepeatPatternDim", "Exif.Image.CFAPattern",
"Exif.Image.BatteryLevel", "Exif.Image.Copyright", "Exif.Image.ExposureTime",
"Exif.Image.FNumber", "Exif.Image.IPTCNAA", "Exif.Image.ImageResources",
"Exif.Image.ExifTag", "Exif.Image.InterColorProfile", "Exif.Image.ExposureProgram",
"Exif.Image.SpectralSensitivity", "Exif.Image.GPSTag", "Exif.Image.ISOSpeedRatings",
"Exif.Image.OECF", "Exif.Image.Interlace", "Exif.Image.TimeZoneOffset",
"Exif.Image.SelfTimerMode", "Exif.Image.DateTimeOriginal", "Exif.Image.CompressedBitsPerPixel",
"Exif.Image.ShutterSpeedValue", "Exif.Image.ApertureValue", "Exif.Image.BrightnessValue",
"Exif.Image.ExposureBiasValue", "Exif.Image.MaxApertureValue",
"Exif.Image.SubjectDistance", "Exif.Image.MeteringMode", "Exif.Image.LightSource",
"Exif.Image.Flash", "Exif.Image.FocalLength", "Exif.Image.FlashEnergy",
"Exif.Image.SpatialFrequencyResponse", "Exif.Image.Noise", "Exif.Image.FocalPlaneXResolution",
"Exif.Image.FocalPlaneYResolution", "Exif.Image.FocalPlaneResolutionUnit",
"Exif.Image.ImageNumber", "Exif.Image.SecurityClassification",
"Exif.Image.ImageHistory", "Exif.Image.SubjectLocation", "Exif.Image.ExposureIndex",
"Exif.Image.TIFFEPStandardID", "Exif.Image.SensingMethod", "Exif.Image.XPTitle",
"Exif.Image.XPComment", "Exif.Image.XPAuthor", "Exif.Image.XPKeywords",
"Exif.Image.XPSubject", "Exif.Image.PrintImageMatching", "Exif.Image.DNGVersion",
"Exif.Image.DNGBackwardVersion", "Exif.Image.UniqueCameraModel",
"Exif.Image.LocalizedCameraModel", "Exif.Image.CFAPlaneColor",
"Exif.Image.CFALayout", "Exif.Image.LinearizationTable", "Exif.Image.BlackLevelRepeatDim",
"Exif.Image.BlackLevel", "Exif.Image.BlackLevelDeltaH", "Exif.Image.BlackLevelDeltaV",
"Exif.Image.WhiteLevel", "Exif.Image.DefaultScale", "Exif.Image.DefaultCropOrigin",
"Exif.Image.DefaultCropSize", "Exif.Image.ColorMatrix1", "Exif.Image.ColorMatrix2",
"Exif.Image.CameraCalibration1", "Exif.Image.CameraCalibration2",
"Exif.Image.ReductionMatrix1", "Exif.Image.ReductionMatrix2",
"Exif.Image.AnalogBalance", "Exif.Image.AsShotNeutral", "Exif.Image.AsShotWhiteXY",
"Exif.Image.BaselineExposure", "Exif.Image.BaselineNoise", "Exif.Image.BaselineSharpness",
"Exif.Image.BayerGreenSplit", "Exif.Image.LinearResponseLimit",
"Exif.Image.CameraSerialNumber", "Exif.Image.LensInfo", "Exif.Image.ChromaBlurRadius",
"Exif.Image.AntiAliasStrength", "Exif.Image.ShadowScale", "Exif.Image.DNGPrivateData",
"Exif.Image.MakerNoteSafety", "Exif.Image.CalibrationIlluminant1",
"Exif.Image.CalibrationIlluminant2", "Exif.Image.BestQualityScale",
"Exif.Image.RawDataUniqueID", "Exif.Image.OriginalRawFileName",
"Exif.Image.OriginalRawFileData", "Exif.Image.ActiveArea", "Exif.Image.MaskedAreas",
"Exif.Image.AsShotICCProfile", "Exif.Image.AsShotPreProfileMatrix",
"Exif.Image.CurrentICCProfile", "Exif.Image.CurrentPreProfileMatrix",
"Exif.Image.ColorimetricReference", "Exif.Image.CameraCalibrationSignature",
"Exif.Image.ProfileCalibrationSignature", "Exif.Image.AsShotProfileName",
"Exif.Image.NoiseReductionApplied", "Exif.Image.ProfileName",
"Exif.Image.ProfileHueSatMapDims", "Exif.Image.ProfileHueSatMapData1",
"Exif.Image.ProfileHueSatMapData2", "Exif.Image.ProfileToneCurve",
"Exif.Image.ProfileEmbedPolicy", "Exif.Image.ProfileCopyright",
"Exif.Image.ForwardMatrix1", "Exif.Image.ForwardMatrix2", "Exif.Image.PreviewApplicationName",
"Exif.Image.PreviewApplicationVersion", "Exif.Image.PreviewSettingsName",
"Exif.Image.PreviewSettingsDigest", "Exif.Image.PreviewColorSpace",
"Exif.Image.PreviewDateTime", "Exif.Image.RawImageDigest", "Exif.Image.OriginalRawFileDigest",
"Exif.Image.SubTileBlockSize", "Exif.Image.RowInterleaveFactor",
"Exif.Image.ProfileLookTableDims", "Exif.Image.ProfileLookTableData",
"Exif.Image.OpcodeList1", "Exif.Image.OpcodeList2", "Exif.Image.OpcodeList3",
"Exif.Image.NoiseProfile", "Exif.Photo.ExposureTime", "Exif.Photo.FNumber",
"Exif.Photo.ExposureProgram", "Exif.Photo.SpectralSensitivity",
"Exif.Photo.ISOSpeedRatings", "Exif.Photo.OECF", "Exif.Photo.SensitivityType",
"Exif.Photo.StandardOutputSensitivity", "Exif.Photo.RecommendedExposureIndex",
"Exif.Photo.ISOSpeed", "Exif.Photo.ISOSpeedLatitudeyyy", "Exif.Photo.ISOSpeedLatitudezzz",
"Exif.Photo.ExifVersion", "Exif.Photo.DateTimeOriginal", "Exif.Photo.DateTimeDigitized",
"Exif.Photo.ComponentsConfiguration", "Exif.Photo.CompressedBitsPerPixel",
"Exif.Photo.ShutterSpeedValue", "Exif.Photo.ApertureValue", "Exif.Photo.BrightnessValue",
"Exif.Photo.ExposureBiasValue", "Exif.Photo.MaxApertureValue",
"Exif.Photo.SubjectDistance", "Exif.Photo.MeteringMode", "Exif.Photo.LightSource",
"Exif.Photo.Flash", "Exif.Photo.FocalLength", "Exif.Photo.SubjectArea",
"Exif.Photo.MakerNote", "Exif.Photo.UserComment", "Exif.Photo.SubSecTime",
"Exif.Photo.SubSecTimeOriginal", "Exif.Photo.SubSecTimeDigitized",
"Exif.Photo.FlashpixVersion", "Exif.Photo.ColorSpace", "Exif.Photo.PixelXDimension",
"Exif.Photo.PixelYDimension", "Exif.Photo.RelatedSoundFile",
"Exif.Photo.InteroperabilityTag", "Exif.Photo.FlashEnergy", "Exif.Photo.SpatialFrequencyResponse",
"Exif.Photo.FocalPlaneXResolution", "Exif.Photo.FocalPlaneYResolution",
"Exif.Photo.FocalPlaneResolutionUnit", "Exif.Photo.SubjectLocation",
"Exif.Photo.ExposureIndex", "Exif.Photo.SensingMethod", "Exif.Photo.FileSource",
"Exif.Photo.SceneType", "Exif.Photo.CFAPattern", "Exif.Photo.CustomRendered",
"Exif.Photo.ExposureMode", "Exif.Photo.WhiteBalance", "Exif.Photo.DigitalZoomRatio",
"Exif.Photo.FocalLengthIn35mmFilm", "Exif.Photo.SceneCaptureType",
"Exif.Photo.GainControl", "Exif.Photo.Contrast", "Exif.Photo.Saturation",
"Exif.Photo.Sharpness", "Exif.Photo.DeviceSettingDescription",
"Exif.Photo.SubjectDistanceRange", "Exif.Photo.ImageUniqueID",
"Exif.Photo.CameraOwnerName", "Exif.Photo.BodySerialNumber",
"Exif.Photo.LensSpecification", "Exif.Photo.LensMake", "Exif.Photo.LensModel",
"Exif.Photo.LensSerialNumber", "Exif.Iop.InteroperabilityIndex",
"Exif.Iop.InteroperabilityVersion", "Exif.Iop.RelatedImageFileFormat",
"Exif.Iop.RelatedImageWidth", "Exif.Iop.RelatedImageLength",
"Exif.GPSInfo.GPSVersionID", "Exif.GPSInfo.GPSLatitudeRef", "Exif.GPSInfo.GPSLatitude",
"Exif.GPSInfo.GPSLongitudeRef", "Exif.GPSInfo.GPSLongitude",
"Exif.GPSInfo.GPSAltitudeRef", "Exif.GPSInfo.GPSAltitude", "Exif.GPSInfo.GPSTimeStamp",
"Exif.GPSInfo.GPSSatellites", "Exif.GPSInfo.GPSStatus", "Exif.GPSInfo.GPSMeasureMode",
"Exif.GPSInfo.GPSDOP", "Exif.GPSInfo.GPSSpeedRef", "Exif.GPSInfo.GPSSpeed",
"Exif.GPSInfo.GPSTrackRef", "Exif.GPSInfo.GPSTrack", "Exif.GPSInfo.GPSImgDirectionRef",
"Exif.GPSInfo.GPSImgDirection", "Exif.GPSInfo.GPSMapDatum", "Exif.GPSInfo.GPSDestLatitudeRef",
"Exif.GPSInfo.GPSDestLatitude", "Exif.GPSInfo.GPSDestLongitudeRef",
"Exif.GPSInfo.GPSDestLongitude", "Exif.GPSInfo.GPSDestBearingRef",
"Exif.GPSInfo.GPSDestBearing", "Exif.GPSInfo.GPSDestDistanceRef",
"Exif.GPSInfo.GPSDestDistance", "Exif.GPSInfo.GPSProcessingMethod",
"Exif.GPSInfo.GPSAreaInformation", "Exif.GPSInfo.GPSDateStamp",
"Exif.GPSInfo.GPSDifferential"), type = c("ascii", "long", "short",
"long", "long", "short", "short", "short", "short", "short",
"short", "short", "ascii", "ascii", "ascii", "ascii", "long",
"short", "short", "long", "long", "rational", "rational", "short",
"short", "short", "long", "long", "short", "short", "short",
"ascii", "ascii", "ascii", "ascii", "short", "rational", "rational",
"short", "short", "short", "short", "short", "short", "long",
"short", "ascii", "short", "byte", "ascii", "short", "short",
"short", "short", "short", "byte", "sshort", "sshort", "short",
"undefined", "short", "long", "long", "long", "short", "short",
"short", "long", "long", "long", "rational", "short", "short",
"rational", "byte", "short", "short", "ascii", "short", "byte",
"rational", "ascii", "rational", "rational", "long", "byte",
"long", "undefined", "short", "ascii", "long", "short", "undefined",
"short", "sshort", "short", "ascii", "rational", "srational",
"rational", "srational", "srational", "rational", "srational",
"short", "short", "short", "rational", "rational", "undefined",
"undefined", "rational", "rational", "short", "long", "ascii",
"ascii", "short", "rational", "byte", "short", "byte", "byte",
"byte", "byte", "byte", "undefined", "byte", "byte", "ascii",
"byte", "byte", "short", "short", "short", "rational", "srational",
"srational", "short", "rational", "short", "short", "srational",
"srational", "srational", "srational", "srational", "srational",
"rational", "short", "rational", "srational", "rational", "rational",
"long", "rational", "ascii", "rational", "rational", "rational",
"srational", "byte", "short", "short", "short", "rational", "byte",
"byte", "undefined", "short", "short", "undefined", "srational",
"undefined", "srational", "short", "byte", "byte", "byte", "rational",
"byte", "long", "float", "float", "float", "long", "byte", "srational",
"srational", "byte", "byte", "byte", "byte", "long", "ascii",
"undefined", "undefined", "long", "long", "long", "float", "undefined",
"undefined", "undefined", "double", "rational", "rational", "short",
"ascii", "short", "undefined", "short", "long", "long", "long",
"long", "long", "undefined", "ascii", "ascii", "undefined", "rational",
"srational", "rational", "srational", "srational", "rational",
"rational", "short", "short", "short", "rational", "short", "undefined",
"comment", "ascii", "ascii", "ascii", "undefined", "short", "long",
"long", "ascii", "long", "rational", "undefined", "rational",
"rational", "short", "short", "rational", "short", "undefined",
"undefined", "undefined", "short", "short", "short", "rational",
"short", "short", "short", "short", "short", "short", "undefined",
"short", "ascii", "ascii", "ascii", "rational", "ascii", "ascii",
"ascii", "ascii", "undefined", "ascii", "long", "long", "byte",
"ascii", "rational", "ascii", "rational", "byte", "rational",
"rational", "ascii", "ascii", "ascii", "rational", "ascii", "rational",
"ascii", "rational", "ascii", "rational", "ascii", "ascii", "rational",
"ascii", "rational", "ascii", "rational", "ascii", "rational",
"undefined", "undefined", "ascii", "short"), description = c("The name and version of the software used to post-process the picture.",
"A general indication of the kind of data contained in this subfile.",
"A general indication of the kind of data contained in this subfile. This field is deprecated. The NewSubfileType field should be used instead.",
"The number of columns of image data, equal to the number of pixels per row. In JPEG compressed data a JPEG marker is used instead of this tag.",
"The number of rows of image data. In JPEG compressed data a JPEG marker is used instead of this tag.",
"The number of bits per image component. In this standard each component of the image is 8 bits, so the value for this tag is 8. See also <SamplesPerPixel>. In JPEG compressed data a JPEG marker is used instead of this tag.",
"The compression scheme used for the image data. When a primary image is JPEG compressed, this designation is not necessary and is omitted. When thumbnails use JPEG compression, this tag value is set to 6.",
"The pixel composition. In JPEG compressed data a JPEG marker is used instead of this tag.",
"For black and white TIFF files that represent shades of gray, the technique used to convert from gray to black and white pixels.",
"The width of the dithering or halftoning matrix used to create a dithered or halftoned bilevel file.",
"The length of the dithering or halftoning matrix used to create a dithered or halftoned bilevel file.",
"The logical order of bits within a byte", "The name of the document from which this image was scanned",
"A character string giving the title of the image. It may be a comment such as \"1988 company picnic\" or the like. Two-bytes character codes cannot be used. When a 2-bytes code is necessary, the Exif Private tag <UserComment> is to be used.",
"The manufacturer of the recording equipment. This is the manufacturer of the DSC, scanner, video digitizer or other equipment that generated the image. When the field is left blank, it is treated as unknown.",
"The model name or model number of the equipment. This is the model name or number of the DSC, scanner, video digitizer or other equipment that generated the image. When the field is left blank, it is treated as unknown.",
"For each strip, the byte offset of that strip. It is recommended that this be selected so the number of strip bytes does not exceed 64 Kbytes. With JPEG compressed data this designation is not needed and is omitted. See also <RowsPerStrip> and <StripByteCounts>.",
"The image orientation viewed in terms of rows and columns.",
"The number of components per pixel. Since this standard applies to RGB and YCbCr images, the value set for this tag is 3. In JPEG compressed data a JPEG marker is used instead of this tag.",
"The number of rows per strip. This is the number of rows in the image of one strip when an image is divided into strips. With JPEG compressed data this designation is not needed and is omitted. See also <StripOffsets> and <StripByteCounts>.",
"The total number of bytes in each strip. With JPEG compressed data this designation is not needed and is omitted.",
"The number of pixels per <ResolutionUnit> in the <ImageWidth> direction. When the image resolution is unknown, 72 [dpi] is designated.",
"The number of pixels per <ResolutionUnit> in the <ImageLength> direction. The same value as <XResolution> is designated.",
"Indicates whether pixel components are recorded in a chunky or planar format. In JPEG compressed files a JPEG marker is used instead of this tag. If this field does not exist, the TIFF default of 1 (chunky) is assumed.",
"The precision of the information contained in the GrayResponseCurve.",
"For grayscale data, the optical density of each possible pixel value.",
"T.4-encoding options.", "T.6-encoding options.", "The unit for measuring <XResolution> and <YResolution>. The same unit is used for both <XResolution> and <YResolution>. If the image resolution is unknown, 2 (inches) is designated.",
"The page number of the page from which this image was scanned.",
"A transfer function for the image, described in tabular style. Normally this tag is not necessary, since color space is specified in the color space information tag (<ColorSpace>).",
"This tag records the name and version of the software or firmware of the camera or image input device used to generate the image. The detailed format is not specified, but it is recommended that the example shown below be followed. When the field is left blank, it is treated as unknown.",
"The date and time of image creation. In Exif standard, it is the date and time the file was changed.",
"This tag records the name of the camera owner, photographer or image creator. The detailed format is not specified, but it is recommended that the information be written as in the example below for ease of Interoperability. When the field is left blank, it is treated as unknown. Ex.) \"Camera owner, John Smith; Photographer, Michael Brown; Image creator, Ken James\"",
"This tag records information about the host computer used to generate the image.",
"A predictor is a mathematical operator that is applied to the image data before an encoding scheme is applied.",
"The chromaticity of the white point of the image. Normally this tag is not necessary, since color space is specified in the colorspace information tag (<ColorSpace>).",
"The chromaticity of the three primary colors of the image. Normally this tag is not necessary, since colorspace is specified in the colorspace information tag (<ColorSpace>).",
"A color map for palette color images. This field defines a Red-Green-Blue color map (often called a lookup table) for palette-color images. In a palette-color image, a pixel value is used to index into an RGB lookup table.",
"The purpose of the HalftoneHints field is to convey to the halftone function the range of gray levels within a colorimetrically-specified image that should retain tonal detail.",
"The tile width in pixels. This is the number of columns in each tile.",
"The tile length (height) in pixels. This is the number of rows in each tile.",
"For each tile, the byte offset of that tile, as compressed and stored on disk. The offset is specified with respect to the beginning of the TIFF file. Note that this implies that each tile has a location independent of the locations of other tiles.",
"For each tile, the number of (compressed) bytes in that tile. See TileOffsets for a description of how the byte counts are ordered.",
"Defined by Adobe Corporation to enable TIFF Trees within a TIFF file.",
"The set of inks used in a separated (PhotometricInterpretation=5) image.",
"The name of each ink used in a separated (PhotometricInterpretation=5) image.",
"The number of inks. Usually equal to SamplesPerPixel, unless there are extra samples.",
"The component values that correspond to a 0% dot and 100% dot.",
"A description of the printing environment for which this separation is intended.",
"Specifies that each pixel has m extra components whose interpretation is defined by one of the values listed below.",
"This field specifies how to interpret each data sample in a pixel.",
"This field specifies the minimum sample value.", "This field specifies the maximum sample value.",
"Expands the range of the TransferFunction", "A TIFF ClipPath is intended to mirror the essentials of PostScript's path creation functionality.",
"The number of units that span the width of the image, in terms of integer ClipPath coordinates.",
"The number of units that span the height of the image, in terms of integer ClipPath coordinates.",
"Indexed images are images where the 'pixels' do not represent color values, but rather an index (usually 8-bit) into a separate color table, the ColorMap.",
"This optional tag may be used to encode the JPEG quantization and Huffman tables for subsequent use by the JPEG decompression process.",
"OPIProxy gives information concerning whether this image is a low-resolution proxy of a high-resolution image (Adobe OPI).",
"This field indicates the process used to produce the compressed data",
"The offset to the start byte (SOI) of JPEG compressed thumbnail data. This is not used for primary image JPEG data.",
"The number of bytes of JPEG compressed thumbnail data. This is not used for primary image JPEG data. JPEG thumbnails are not divided but are recorded as a continuous JPEG bitstream from SOI to EOI. Appn and COM markers should not be recorded. Compressed thumbnails must be recorded in no more than 64 Kbytes, including all other data to be recorded in APP1.",
"This Field indicates the length of the restart interval used in the compressed image data.",
"This Field points to a list of lossless predictor-selection values, one per component.",
"This Field points to a list of point transform values, one per component.",
"This Field points to a list of offsets to the quantization tables, one per component.",
"This Field points to a list of offsets to the DC Huffman tables or the lossless Huffman tables, one per component.",
"This Field points to a list of offsets to the Huffman AC tables, one per component.",
"The matrix coefficients for transformation from RGB to YCbCr image data. No default is given in TIFF; but here the value given in Appendix E, \"Color Space Guidelines\", is used as the default. The color space is declared in a color space information tag, with the default being the value that gives the optimal image characteristics Interoperability this condition.",
"The sampling ratio of chrominance components in relation to the luminance component. In JPEG compressed data a JPEG marker is used instead of this tag.",
"The position of chrominance components in relation to the luminance component. This field is designated only for JPEG compressed data or uncompressed YCbCr data. The TIFF default is 1 (centered); but when Y:Cb:Cr = 4:2:2 it is recommended in this standard that 2 (co-sited) be used to record data, in order to improve the image quality when viewed on TV systems. When this field does not exist, the reader shall assume the TIFF default. In the case of Y:Cb:Cr = 4:2:0, the TIFF default (centered) is recommended. If the reader does not have the capability of supporting both kinds of <YCbCrPositioning>, it shall follow the TIFF default regardless of the value in this field. It is preferable that readers be able to support both centered and co-sited positioning.",
"The reference black point value and reference white point value. No defaults are given in TIFF, but the values below are given as defaults here. The color space is declared in a color space information tag, with the default being the value that gives the optimal image characteristics Interoperability these conditions.",
"XMP Metadata (Adobe technote 9-14-02)", "Rating tag used by Windows",
"Rating tag used by Windows, value in percent", "ImageID is the full pathname of the original, high-resolution image, or any other identifying string that uniquely identifies the original image (Adobe OPI).",
"Contains two values representing the minimum rows and columns to define the repeating patterns of the color filter array",
"Indicates the color filter array (CFA) geometric pattern of the image sensor when a one-chip color area sensor is used. It does not apply to all sensing methods",
"Contains a value of the battery level as a fraction or string",
"Copyright information. In this standard the tag is used to indicate both the photographer and editor copyrights. It is the copyright notice of the person or organization claiming rights to the image. The Interoperability copyright statement including date and rights should be written in this field; e.g., \"Copyright, John Smith, 19xx. All rights reserved.\". In this standard the field records both the photographer and editor copyrights, with each recorded in a separate part of the statement. When there is a clear distinction between the photographer and editor copyrights, these are to be written in the order of photographer followed by editor copyright, separated by NULL (in this case since the statement also ends with a NULL, there are two NULL codes). When only the photographer copyright is given, it is terminated by one NULL code. When only the editor copyright is given, the photographer copyright part consists of one space followed by a terminating NULL code, then the editor copyright is given. When the field is left blank, it is treated as unknown.",
"Exposure time, given in seconds.", "The F number.", "Contains an IPTC/NAA record",
"Contains information embedded by the Adobe Photoshop application",
"A pointer to the Exif IFD. Interoperability, Exif IFD has the same structure as that of the IFD specified in TIFF. ordinarily, however, it does not contain image data as in the case of TIFF.",
"Contains an InterColor Consortium (ICC) format color space characterization/profile",
"The class of the program used by the camera to set exposure when the picture is taken.",
"Indicates the spectral sensitivity of each channel of the camera used.",
"A pointer to the GPS Info IFD. The Interoperability structure of the GPS Info IFD, like that of Exif IFD, has no image data.",
"Indicates the ISO Speed and ISO Latitude of the camera or input device as specified in ISO 12232.",
"Indicates the Opto-Electric Conversion Function (OECF) specified in ISO 14524.",
"Indicates the field number of multifield images.", "This optional tag encodes the time zone of the camera clock (relativeto Greenwich Mean Time) used to create the DataTimeOriginal tag-valuewhen the picture was taken. It may also contain the time zone offsetof the clock used to create the DateTime tag-value when the image wasmodified.",
"Number of seconds image capture was delayed from button press.",
"The date and time when the original image data was generated.",
"Specific to compressed data; states the compressed bits per pixel.",
"Shutter speed.", "The lens aperture.", "The value of brightness.",
"The exposure bias.", "The smallest F number of the lens.", "The distance to the subject, given in meters.",
"The metering mode.", "The kind of light source.", "Indicates the status of flash when the image was shot.",
"The actual focal length of the lens, in mm.", "Amount of flash energy (BCPS).",
"SFR of the camera.", "Noise measurement values.", "Number of pixels per FocalPlaneResolutionUnit (37392) in ImageWidth direction for main image.",
"Number of pixels per FocalPlaneResolutionUnit (37392) in ImageLength direction for main image.",
"Unit of measurement for FocalPlaneXResolution(37390) and FocalPlaneYResolution(37391).",
"Number assigned to an image, e.g., in a chained image burst.",
"Security classification assigned to the image.", "Record of what has been done to the image.",
"Indicates the location and area of the main subject in the overall scene.",
"Encodes the camera exposure index setting when image was captured.",
"Contains four ASCII characters representing the TIFF/EP standard version of a TIFF/EP file, eg '1', '0', '0', '0'",
"Type of image sensor.", "Title tag used by Windows, encoded in UCS2",
"Comment tag used by Windows, encoded in UCS2", "Author tag used by Windows, encoded in UCS2",
"Keywords tag used by Windows, encoded in UCS2", "Subject tag used by Windows, encoded in UCS2",
"Print Image Matching, description needed.", "This tag encodes the DNG four-tier version number. For files compliant with version 1.1.0.0 of the DNG specification, this tag should contain the bytes: 1, 1, 0, 0.",
"This tag specifies the oldest version of the Digital Negative specification for which a file is compatible. Readers shouldnot attempt to read a file if this tag specifies a version number that is higher than the version number of the specification the reader was based on.  In addition to checking the version tags, readers should, for all tags, check the types, counts, and values, to verify it is able to correctly read the file.",
"Defines a unique, non-localized name for the camera model that created the image in the raw file. This name should include the manufacturer's name to avoid conflicts, and should not be localized, even if the camera name itself is localized for different markets (see LocalizedCameraModel). This string may be used by reader software to index into per-model preferences and replacement profiles.",
"Similar to the UniqueCameraModel field, except the name can be localized for different markets to match the localization of the camera name.",
"Provides a mapping between the values in the CFAPattern tag and the plane numbers in LinearRaw space. This is a required tag for non-RGB CFA images.",
"Describes the spatial layout of the CFA.", "Describes a lookup table that maps stored values into linear values. This tag is typically used to increase compression ratios by storing the raw data in a non-linear, more visually uniform space with fewer total encoding levels. If SamplesPerPixel is not equal to one, this single table applies to all the samples for each pixel.",
"Specifies repeat pattern size for the BlackLevel tag.", "Specifies the zero light (a.k.a. thermal black or black current) encoding level, as a repeating pattern. The origin of this pattern is the top-left corner of the ActiveArea rectangle. The values are stored in row-column-sample scan order.",
"If the zero light encoding level is a function of the image column, BlackLevelDeltaH specifies the difference between the zero light encoding level for each column and the baseline zero light encoding level. If SamplesPerPixel is not equal to one, this single table applies to all the samples for each pixel.",
"If the zero light encoding level is a function of the image row, this tag specifies the difference between the zero light encoding level for each row and the baseline zero light encoding level. If SamplesPerPixel is not equal to one, this single table applies to all the samples for each pixel.",
"This tag specifies the fully saturated encoding level for the raw sample values. Saturation is caused either by the sensor itself becoming highly non-linear in response, or by the camera's analog to digital converter clipping.",
"DefaultScale is required for cameras with non-square pixels. It specifies the default scale factors for each direction to convert the image to square pixels. Typically these factors are selected to approximately preserve total pixel count. For CFA images that use CFALayout equal to 2, 3, 4, or 5, such as the Fujifilm SuperCCD, these two values should usually differ by a factor of 2.0.",
"Raw images often store extra pixels around the edges of the final image. These extra pixels help prevent interpolation artifacts near the edges of the final image. DefaultCropOrigin specifies the origin of the final image area, in raw image coordinates (i.e., before the DefaultScale has been applied), relative to the top-left corner of the ActiveArea rectangle.",
"Raw images often store extra pixels around the edges of the final image. These extra pixels help prevent interpolation artifacts near the edges of the final image. DefaultCropSize specifies the size of the final image area, in raw image coordinates (i.e., before the DefaultScale has been applied).",
"ColorMatrix1 defines a transformation matrix that converts XYZ values to reference camera native color space values, under the first calibration illuminant. The matrix values are stored in row scan order. The ColorMatrix1 tag is required for all non-monochrome DNG files.",
"ColorMatrix2 defines a transformation matrix that converts XYZ values to reference camera native color space values, under the second calibration illuminant. The matrix values are stored in row scan order.",
"CameraCalibration1 defines a calibration matrix that transforms reference camera native space values to individual camera native space values under the first calibration illuminant. The matrix is stored in row scan order. This matrix is stored separately from the matrix specified by the ColorMatrix1 tag to allow raw converters to swap in replacement color matrices based on UniqueCameraModel tag, while still taking advantage of any per-individual camera calibration performed by the camera manufacturer.",
"CameraCalibration2 defines a calibration matrix that transforms reference camera native space values to individual camera native space values under the second calibration illuminant. The matrix is stored in row scan order. This matrix is stored separately from the matrix specified by the ColorMatrix2 tag to allow raw converters to swap in replacement color matrices based on UniqueCameraModel tag, while still taking advantage of any per-individual camera calibration performed by the camera manufacturer.",
"ReductionMatrix1 defines a dimensionality reduction matrix for use as the first stage in converting color camera native space values to XYZ values, under the first calibration illuminant. This tag may only be used if ColorPlanes is greater than 3. The matrix is stored in row scan order.",
"ReductionMatrix2 defines a dimensionality reduction matrix for use as the first stage in converting color camera native space values to XYZ values, under the second calibration illuminant. This tag may only be used if ColorPlanes is greater than 3. The matrix is stored in row scan order.",
"Normally the stored raw values are not white balanced, since any digital white balancing will reduce the dynamic range of the final image if the user decides to later adjust the white balance; however, if camera hardware is capable of white balancing the color channels before the signal is digitized, it can improve the dynamic range of the final image. AnalogBalance defines the gain, either analog (recommended) or digital (not recommended) that has been applied the stored raw values.",
"Specifies the selected white balance at time of capture, encoded as the coordinates of a perfectly neutral color in linear reference space values. The inclusion of this tag precludes the inclusion of the AsShotWhiteXY tag.",
"Specifies the selected white balance at time of capture, encoded as x-y chromaticity coordinates. The inclusion of this tag precludes the inclusion of the AsShotNeutral tag.",
"Camera models vary in the trade-off they make between highlight headroom and shadow noise. Some leave a significant amount of highlight headroom during a normal exposure. This allows significant negative exposure compensation to be applied during raw conversion, but also means normal exposures will contain more shadow noise. Other models leave less headroom during normal exposures. This allows for less negative exposure compensation, but results in lower shadow noise for normal exposures. Because of these differences, a raw converter needs to vary the zero point of its exposure compensation control from model to model. BaselineExposure specifies by how much (in EV units) to move the zero point. Positive values result in brighter default results, while negative values result in darker default results.",
"Specifies the relative noise level of the camera model at a baseline ISO value of 100, compared to a reference camera model. Since noise levels tend to vary approximately with the square root of the ISO value, a raw converter can use this value, combined with the current ISO, to estimate the relative noise level of the current image.",
"Specifies the relative amount of sharpening required for this camera model, compared to a reference camera model. Camera models vary in the strengths of their anti-aliasing filters. Cameras with weak or no filters require less sharpening than cameras with strong anti-aliasing filters.",
"Only applies to CFA images using a Bayer pattern filter array. This tag specifies, in arbitrary units, how closely the values of the green pixels in the blue/green rows track the values of the green pixels in the red/green rows. A value of zero means the two kinds of green pixels track closely, while a non-zero value means they sometimes diverge. The useful range for this tag is from 0 (no divergence) to about 5000 (quite large divergence).",
"Some sensors have an unpredictable non-linearity in their response as they near the upper limit of their encoding range. This non-linearity results in color shifts in the highlight areas of the resulting image unless the raw converter compensates for this effect. LinearResponseLimit specifies the fraction of the encoding range above which the response may become significantly non-linear.",
"CameraSerialNumber contains the serial number of the camera or camera body that captured the image.",
"Contains information about the lens that captured the image. If the minimum f-stops are unknown, they should be encoded as 0/0.",
"ChromaBlurRadius provides a hint to the DNG reader about how much chroma blur should be applied to the image. If this tag is omitted, the reader will use its default amount of chroma blurring. Normally this tag is only included for non-CFA images, since the amount of chroma blur required for mosaic images is highly dependent on the de-mosaic algorithm, in which case the DNG reader's default value is likely optimized for its particular de-mosaic algorithm.",
"Provides a hint to the DNG reader about how strong the camera's anti-alias filter is. A value of 0.0 means no anti-alias filter (i.e., the camera is prone to aliasing artifacts with some subjects), while a value of 1.0 means a strong anti-alias filter (i.e., the camera almost never has aliasing artifacts).",
"This tag is used by Adobe Camera Raw to control the sensitivity of its 'Shadows' slider.",
"Provides a way for camera manufacturers to store private data in the DNG file for use by their own raw converters, and to have that data preserved by programs that edit DNG files.",
"MakerNoteSafety lets the DNG reader know whether the EXIF MakerNote tag is safe to preserve along with the rest of the EXIF data. File browsers and other image management software processing an image with a preserved MakerNote should be aware that any thumbnail image embedded in the MakerNote may be stale, and may not reflect the current state of the full size image.",
"The illuminant used for the first set of color calibration tags (ColorMatrix1, CameraCalibration1, ReductionMatrix1). The legal values for this tag are the same as the legal values for the LightSource EXIF tag.",
"The illuminant used for an optional second set of color calibration tags (ColorMatrix2, CameraCalibration2, ReductionMatrix2). The legal values for this tag are the same as the legal values for the CalibrationIlluminant1 tag; however, if both are included, neither is allowed to have a value of 0 (unknown).",
"For some cameras, the best possible image quality is not achieved by preserving the total pixel count during conversion. For example, Fujifilm SuperCCD images have maximum detail when their total pixel count is doubled. This tag specifies the amount by which the values of the DefaultScale tag need to be multiplied to achieve the best quality image size.",
"This tag contains a 16-byte unique identifier for the raw image data in the DNG file. DNG readers can use this tag to recognize a particular raw image, even if the file's name or the metadata contained in the file has been changed. If a DNG writer creates such an identifier, it should do so using an algorithm that will ensure that it is very unlikely two different images will end up having the same identifier.",
"If the DNG file was converted from a non-DNG raw file, then this tag contains the file name of that original raw file.",
"If the DNG file was converted from a non-DNG raw file, then this tag contains the compressed contents of that original raw file. The contents of this tag always use the big-endian byte order. The tag contains a sequence of data blocks. Future versions of the DNG specification may define additional data blocks, so DNG readers should ignore extra bytes when parsing this tag. DNG readers should also detect the case where data blocks are missing from the end of the sequence, and should assume a default value for all the missing blocks. There are no padding or alignment bytes between data blocks.",
"This rectangle defines the active (non-masked) pixels of the sensor. The order of the rectangle coordinates is: top, left, bottom, right.",
"This tag contains a list of non-overlapping rectangle coordinates of fully masked pixels, which can be optionally used by DNG readers to measure the black encoding level. The order of each rectangle's coordinates is: top, left, bottom, right. If the raw image data has already had its black encoding level subtracted, then this tag should not be used, since the masked pixels are no longer useful.",
"This tag contains an ICC profile that, in conjunction with the AsShotPreProfileMatrix tag, provides the camera manufacturer with a way to specify a default color rendering from camera color space coordinates (linear reference values) into the ICC profile connection space. The ICC profile connection space is an output referred colorimetric space, whereas the other color calibration tags in DNG specify a conversion into a scene referred colorimetric space. This means that the rendering in this profile should include any desired tone and gamut mapping needed to convert between scene referred values and output referred values.",
"This tag is used in conjunction with the AsShotICCProfile tag. It specifies a matrix that should be applied to the camera color space coordinates before processing the values through the ICC profile specified in the AsShotICCProfile tag. The matrix is stored in the row scan order. If ColorPlanes is greater than three, then this matrix can (but is not required to) reduce the dimensionality of the color data down to three components, in which case the AsShotICCProfile should have three rather than ColorPlanes input components.",
"This tag is used in conjunction with the CurrentPreProfileMatrix tag. The CurrentICCProfile and CurrentPreProfileMatrix tags have the same purpose and usage as the AsShotICCProfile and AsShotPreProfileMatrix tag pair, except they are for use by raw file editors rather than camera manufacturers.",
"This tag is used in conjunction with the CurrentICCProfile tag. The CurrentICCProfile and CurrentPreProfileMatrix tags have the same purpose and usage as the AsShotICCProfile and AsShotPreProfileMatrix tag pair, except they are for use by raw file editors rather than camera manufacturers.",
"The DNG color model documents a transform between camera colors and CIE XYZ values. This tag describes the colorimetric reference for the CIE XYZ values. 0 = The XYZ values are scene-referred. 1 = The XYZ values are output-referred, using the ICC profile perceptual dynamic range. This tag allows output-referred data to be stored in DNG files and still processed correctly by DNG readers.",
"A UTF-8 encoded string associated with the CameraCalibration1 and CameraCalibration2 tags. The CameraCalibration1 and CameraCalibration2 tags should only be used in the DNG color transform if the string stored in the CameraCalibrationSignature tag exactly matches the string stored in the ProfileCalibrationSignature tag for the selected camera profile.",
"A UTF-8 encoded string associated with the camera profile tags. The CameraCalibration1 and CameraCalibration2 tags should only be used in the DNG color transfer if the string stored in the CameraCalibrationSignature tag exactly matches the string stored in the ProfileCalibrationSignature tag for the selected camera profile.",
"A UTF-8 encoded string containing the name of the \"as shot\" camera profile, if any.",
"This tag indicates how much noise reduction has been applied to the raw data on a scale of 0.0 to 1.0. A 0.0 value indicates that no noise reduction has been applied. A 1.0 value indicates that the \"ideal\" amount of noise reduction has been applied, i.e. that the DNG reader should not apply additional noise reduction by default. A value of 0/0 indicates that this parameter is unknown.",
"A UTF-8 encoded string containing the name of the camera profile. This tag is optional if there is only a single camera profile stored in the file but is required for all camera profiles if there is more than one camera profile stored in the file.",
"This tag specifies the number of input samples in each dimension of the hue/saturation/value mapping tables. The data for these tables are stored in ProfileHueSatMapData1 and ProfileHueSatMapData2 tags. The most common case has ValueDivisions equal to 1, so only hue and saturation are used as inputs to the mapping table.",
"This tag contains the data for the first hue/saturation/value mapping table. Each entry of the table contains three 32-bit IEEE floating-point values. The first entry is hue shift in degrees; the second entry is saturation scale factor; and the third entry is a value scale factor. The table entries are stored in the tag in nested loop order, with the value divisions in the outer loop, the hue divisions in the middle loop, and the saturation divisions in the inner loop. All zero input saturation entries are required to have a value scale factor of 1.0.",
"This tag contains the data for the second hue/saturation/value mapping table. Each entry of the table contains three 32-bit IEEE floating-point values. The first entry is hue shift in degrees; the second entry is a saturation scale factor; and the third entry is a value scale factor. The table entries are stored in the tag in nested loop order, with the value divisions in the outer loop, the hue divisions in the middle loop, and the saturation divisions in the inner loop. All zero input saturation entries are required to have a value scale factor of 1.0.",
"This tag contains a default tone curve that can be applied while processing the image as a starting point for user adjustments. The curve is specified as a list of 32-bit IEEE floating-point value pairs in linear gamma. Each sample has an input value in the range of 0.0 to 1.0, and an output value in the range of 0.0 to 1.0. The first sample is required to be (0.0, 0.0), and the last sample is required to be (1.0, 1.0). Interpolated the curve using a cubic spline.",
"This tag contains information about the usage rules for the associated camera profile.",
"A UTF-8 encoded string containing the copyright information for the camera profile. This string always should be preserved along with the other camera profile tags.",
"This tag defines a matrix that maps white balanced camera colors to XYZ D50 colors.",
"This tag defines a matrix that maps white balanced camera colors to XYZ D50 colors.",
"A UTF-8 encoded string containing the name of the application that created the preview stored in the IFD.",
"A UTF-8 encoded string containing the version number of the application that created the preview stored in the IFD.",
"A UTF-8 encoded string containing the name of the conversion settings (for example, snapshot name) used for the preview stored in the IFD.",
"A unique ID of the conversion settings (for example, MD5 digest) used to render the preview stored in the IFD.",
"This tag specifies the color space in which the rendered preview in this IFD is stored. The default value for this tag is sRGB for color previews and Gray Gamma 2.2 for monochrome previews.",
"This tag is an ASCII string containing the name of the date/time at which the preview stored in the IFD was rendered. The date/time is encoded using ISO 8601 format.",
"This tag is an MD5 digest of the raw image data. All pixels in the image are processed in row-scan order. Each pixel is zero padded to 16 or 32 bits deep (16-bit for data less than or equal to 16 bits deep, 32-bit otherwise). The data for each pixel is processed in little-endian byte order.",
"This tag is an MD5 digest of the data stored in the OriginalRawFileData tag.",
"Normally, the pixels within a tile are stored in simple row-scan order. This tag specifies that the pixels within a tile should be grouped first into rectangular blocks of the specified size. These blocks are stored in row-scan order. Within each block, the pixels are stored in row-scan order. The use of a non-default value for this tag requires setting the DNGBackwardVersion tag to at least 1.2.0.0.",
"This tag specifies that rows of the image are stored in interleaved order. The value of the tag specifies the number of interleaved fields. The use of a non-default value for this tag requires setting the DNGBackwardVersion tag to at least 1.2.0.0.",
"This tag specifies the number of input samples in each dimension of a default \"look\" table. The data for this table is stored in the ProfileLookTableData tag.",
"This tag contains a default \"look\" table that can be applied while processing the image as a starting point for user adjustment. This table uses the same format as the tables stored in the ProfileHueSatMapData1 and ProfileHueSatMapData2 tags, and is applied in the same color space. However, it should be applied later in the processing pipe, after any exposure compensation and/or fill light stages, but before any tone curve stage. Each entry of the table contains three 32-bit IEEE floating-point values. The first entry is hue shift in degrees, the second entry is a saturation scale factor, and the third entry is a value scale factor. The table entries are stored in the tag in nested loop order, with the value divisions in the outer loop, the hue divisions in the middle loop, and the saturation divisions in the inner loop. All zero input saturation entries are required to have a value scale factor of 1.0.",
"Specifies the list of opcodes that should be applied to the raw image, as read directly from the file.",
"Specifies the list of opcodes that should be applied to the raw image, just after it has been mapped to linear reference values.",
"Specifies the list of opcodes that should be applied to the raw image, just after it has been demosaiced.",
"NoiseProfile describes the amount of noise in a raw image. Specifically, this tag models the amount of signal-dependent photon (shot) noise and signal-independent sensor readout noise, two common sources of noise in raw images. The model assumes that the noise is white and spatially independent, ignoring fixed pattern effects and other sources of noise (e.g., pixel response non-uniformity, spatially-dependent thermal effects, etc.).",
"Exposure time, given in seconds (sec).", "The F number.", "The class of the program used by the camera to set exposure when the picture is taken.",
"Indicates the spectral sensitivity of each channel of the camera used. The tag value is an ASCII string compatible with the standard developed by the ASTM Technical Committee.",
"Indicates the ISO Speed and ISO Latitude of the camera or input device as specified in ISO 12232.",
"Indicates the Opto-Electoric Conversion Function (OECF) specified in ISO 14524. <OECF> is the relationship between the camera optical input and the image values.",
"The SensitivityType tag indicates which one of the parameters of ISO12232 is the PhotographicSensitivity tag. Although it is an optional tag, it should be recorded when a PhotographicSensitivity tag is recorded. Value = 4, 5, 6, or 7 may be used in case that the values of plural parameters are the same.",
"This tag indicates the standard output sensitivity value of a camera or input device defined in ISO 12232. When recording this tag, the PhotographicSensitivity and SensitivityType tags shall also be recorded.",
"This tag indicates the recommended exposure index value of a camera or input device defined in ISO 12232. When recording this tag, the PhotographicSensitivity and SensitivityType tags shall also be recorded.",
"This tag indicates the ISO speed value of a camera or input device that is defined in ISO 12232. When recording this tag, the PhotographicSensitivity and SensitivityType tags shall also be recorded.",
"This tag indicates the ISO speed latitude yyy value of a camera or input device that is defined in ISO 12232. However, this tag shall not be recorded without ISOSpeed and ISOSpeedLatitudezzz.",
"This tag indicates the ISO speed latitude zzz value of a camera or input device that is defined in ISO 12232. However, this tag shall not be recorded without ISOSpeed and ISOSpeedLatitudeyyy.",
"The version of this standard supported. Nonexistence of this field is taken to mean nonconformance to the standard.",
"The date and time when the original image data was generated. For a digital still camera the date and time the picture was taken are recorded.",
"The date and time when the image was stored as digital data.",
"Information specific to compressed data. The channels of each component are arranged in order from the 1st component to the 4th. For uncompressed data the data arrangement is given in the <PhotometricInterpretation> tag. However, since <PhotometricInterpretation> can only express the order of Y, Cb and Cr, this tag is provided for cases when compressed data uses components other than Y, Cb, and Cr and to enable support of other sequences.",
"Information specific to compressed data. The compression mode used for a compressed image is indicated in unit bits per pixel.",
"Shutter speed. The unit is the APEX (Additive System of Photographic Exposure) setting.",
"The lens aperture. The unit is the APEX value.", "The value of brightness. The unit is the APEX value. Ordinarily it is given in the range of -99.99 to 99.99.",
"The exposure bias. The units is the APEX value. Ordinarily it is given in the range of -99.99 to 99.99.",
"The smallest F number of the lens. The unit is the APEX value. Ordinarily it is given in the range of 00.00 to 99.99, but it is not limited to this range.",
"The distance to the subject, given in meters.", "The metering mode.",
"The kind of light source.", "This tag is recorded when an image is taken using a strobe light (flash).",
"The actual focal length of the lens, in mm. Conversion is not made to the focal length of a 35 mm film camera.",
"This tag indicates the location and area of the main subject in the overall scene.",
"A tag for manufacturers of Exif writers to record any desired information. The contents are up to the manufacturer.",
"A tag for Exif users to write keywords or comments on the image besides those in <ImageDescription>, and without the character code limitations of the <ImageDescription> tag.",
"A tag used to record fractions of seconds for the <DateTime> tag.",
"A tag used to record fractions of seconds for the <DateTimeOriginal> tag.",
"A tag used to record fractions of seconds for the <DateTimeDigitized> tag.",
"The FlashPix format version supported by a FPXR file.", "The color space information tag is always recorded as the color space specifier. Normally sRGB is used to define the color space based on the PC monitor conditions and environment. If a color space other than sRGB is used, Uncalibrated is set. Image data recorded as Uncalibrated can be treated as sRGB when it is converted to FlashPix.",
"Information specific to compressed data. When a compressed file is recorded, the valid width of the meaningful image must be recorded in this tag, whether or not there is padding data or a restart marker. This tag should not exist in an uncompressed file.",
"Information specific to compressed data. When a compressed file is recorded, the valid height of the meaningful image must be recorded in this tag, whether or not there is padding data or a restart marker. This tag should not exist in an uncompressed file. Since data padding is unnecessary in the vertical direction, the number of lines recorded in this valid image height tag will in fact be the same as that recorded in the SOF.",
"This tag is used to record the name of an audio file related to the image data. The only relational information recorded here is the Exif audio file name and extension (an ASCII string consisting of 8 characters + '.' + 3 characters). The path is not recorded.",
"Interoperability IFD is composed of tags which stores the information to ensure the Interoperability and pointed by the following tag located in Exif IFD. The Interoperability structure of Interoperability IFD is the same as TIFF defined IFD structure but does not contain the image data characteristically compared with normal TIFF IFD.",
"Indicates the strobe energy at the time the image is captured, as measured in Beam Candle Power Seconds (BCPS).",
"This tag records the camera or input device spatial frequency table and SFR values in the direction of image width, image height, and diagonal direction, as specified in ISO 12233.",
"Indicates the number of pixels in the image width (X) direction per <FocalPlaneResolutionUnit> on the camera focal plane.",
"Indicates the number of pixels in the image height (V) direction per <FocalPlaneResolutionUnit> on the camera focal plane.",
"Indicates the unit for measuring <FocalPlaneXResolution> and <FocalPlaneYResolution>. This value is the same as the <ResolutionUnit>.",
"Indicates the location of the main subject in the scene. The value of this tag represents the pixel at the center of the main subject relative to the left edge, prior to rotation processing as per the <Rotation> tag. The first value indicates the X column number and second indicates the Y row number.",
"Indicates the exposure index selected on the camera or input device at the time the image is captured.",
"Indicates the image sensor type on the camera or input device.",
"Indicates the image source. If a DSC recorded the image, this tag value of this tag always be set to 3, indicating that the image was recorded on a DSC.",
"Indicates the type of scene. If a DSC recorded the image, this tag value must always be set to 1, indicating that the image was directly photographed.",
"Indicates the color filter array (CFA) geometric pattern of the image sensor when a one-chip color area sensor is used. It does not apply to all sensing methods.",
"This tag indicates the use of special processing on image data, such as rendering geared to output. When special processing is performed, the reader is expected to disable or minimize any further processing.",
"This tag indicates the exposure mode set when the image was shot. In auto-bracketing mode, the camera shoots a series of frames of the same scene at different exposure settings.",
"This tag indicates the white balance mode set when the image was shot.",
"This tag indicates the digital zoom ratio when the image was shot. If the numerator of the recorded value is 0, this indicates that digital zoom was not used.",
"This tag indicates the equivalent focal length assuming a 35mm film camera, in mm. A value of 0 means the focal length is unknown. Note that this tag differs from the <FocalLength> tag.",
"This tag indicates the type of scene that was shot. It can also be used to record the mode in which the image was shot. Note that this differs from the <SceneType> tag.",
"This tag indicates the degree of overall image gain adjustment.",
"This tag indicates the direction of contrast processing applied by the camera when the image was shot.",
"This tag indicates the direction of saturation processing applied by the camera when the image was shot.",
"This tag indicates the direction of sharpness processing applied by the camera when the image was shot.",
"This tag indicates information on the picture-taking conditions of a particular camera model. The tag is used only to indicate the picture-taking conditions in the reader.",
"This tag indicates the distance to the subject.", "This tag indicates an identifier assigned uniquely to each image. It is recorded as an ASCII string equivalent to hexadecimal notation and 128-bit fixed length.",
"This tag records the owner of a camera used in photography as an ASCII string.",
"This tag records the serial number of the body of the camera that was used in photography as an ASCII string.",
"This tag notes minimum focal length, maximum focal length, minimum F number in the minimum focal length, and minimum F number in the maximum focal length, which are specification information for the lens that was used in photography. When the minimum F number is unknown, the notation is 0/0",
"This tag records the lens manufactor as an ASCII string.", "This tag records the lens's model name and model number as an ASCII string.",
"This tag records the serial number of the interchangeable lens that was used in photography as an ASCII string.",
"Indicates the identification of the Interoperability rule. Use \"R98\" for stating ExifR98 Rules. Four bytes used including the termination code (NULL). see the separate volume of Recommended Exif Interoperability Rules (ExifR98) for other tags used for ExifR98.",
"Interoperability version", "File format of image file", "Image width",
"Image height", "Indicates the version of <GPSInfoIFD>. The version is given as 2.0.0.0. This tag is mandatory when <GPSInfo> tag is present. (Note: The <GPSVersionID> tag is given in bytes, unlike the <ExifVersion> tag. When the version is 2.0.0.0, the tag value is 02000000.H).",
"Indicates whether the latitude is north or south latitude. The ASCII value 'N' indicates north latitude, and 'S' is south latitude.",
"Indicates the latitude. The latitude is expressed as three RATIONAL values giving the degrees, minutes, and seconds, respectively. When degrees, minutes and seconds are expressed, the format is dd/1,mm/1,ss/1. When degrees and minutes are used and, for example, fractions of minutes are given up to two decimal places, the format is dd/1,mmmm/100,0/1.",
"Indicates whether the longitude is east or west longitude. ASCII 'E' indicates east longitude, and 'W' is west longitude.",
"Indicates the longitude. The longitude is expressed as three RATIONAL values giving the degrees, minutes, and seconds, respectively. When degrees, minutes and seconds are expressed, the format is ddd/1,mm/1,ss/1. When degrees and minutes are used and, for example, fractions of minutes are given up to two decimal places, the format is ddd/1,mmmm/100,0/1.",
"Indicates the altitude used as the reference altitude. If the reference is sea level and the altitude is above sea level, 0 is given. If the altitude is below sea level, a value of 1 is given and the altitude is indicated as an absolute value in the GSPAltitude tag. The reference unit is meters. Note that this tag is BYTE type, unlike other reference tags.",
"Indicates the altitude based on the reference in GPSAltitudeRef. Altitude is expressed as one RATIONAL value. The reference unit is meters.",
"Indicates the time as UTC (Coordinated Universal Time). <TimeStamp> is expressed as three RATIONAL values giving the hour, minute, and second (atomic clock).",
"Indicates the GPS satellites used for measurements. This tag can be used to describe the number of satellites, their ID number, angle of elevation, azimuth, SNR and other information in ASCII notation. The format is not specified. If the GPS receiver is incapable of taking measurements, value of the tag is set to NULL.",
"Indicates the status of the GPS receiver when the image is recorded. \"A\" means measurement is in progress, and \"V\" means the measurement is Interoperability.",
"Indicates the GPS measurement mode. \"2\" means two-dimensional measurement and \"3\" means three-dimensional measurement is in progress.",
"Indicates the GPS DOP (data degree of precision). An HDOP value is written during two-dimensional measurement, and PDOP during three-dimensional measurement.",
"Indicates the unit used to express the GPS receiver speed of movement. \"K\" \"M\" and \"N\" represents kilometers per hour, miles per hour, and knots.",
"Indicates the speed of GPS receiver movement.", "Indicates the reference for giving the direction of GPS receiver movement. \"T\" denotes true direction and \"M\" is magnetic direction.",
"Indicates the direction of GPS receiver movement. The range of values is from 0.00 to 359.99.",
"Indicates the reference for giving the direction of the image when it is captured. \"T\" denotes true direction and \"M\" is magnetic direction.",
"Indicates the direction of the image when it was captured. The range of values is from 0.00 to 359.99.",
"Indicates the geodetic survey data used by the GPS receiver. If the survey data is restricted to Japan, the value of this tag is \"TOKYO\" or \"WGS-84\".",
"Indicates whether the latitude of the destination point is north or south latitude. The ASCII value \"N\" indicates north latitude, and \"S\" is south latitude.",
"Indicates the latitude of the destination point. The latitude is expressed as three RATIONAL values giving the degrees, minutes, and seconds, respectively. If latitude is expressed as degrees, minutes and seconds, a typical format would be dd/1,mm/1,ss/1. When degrees and minutes are used and, for example, fractions of minutes are given up to two decimal places, the format would be dd/1,mmmm/100,0/1.",
"Indicates whether the longitude of the destination point is east or west longitude. ASCII \"E\" indicates east longitude, and \"W\" is west longitude.",
"Indicates the longitude of the destination point. The longitude is expressed as three RATIONAL values giving the degrees, minutes, and seconds, respectively. If longitude is expressed as degrees, minutes and seconds, a typical format would be ddd/1,mm/1,ss/1. When degrees and minutes are used and, for example, fractions of minutes are given up to two decimal places, the format would be ddd/1,mmmm/100,0/1.",
"Indicates the reference used for giving the bearing to the destination point. \"T\" denotes true direction and \"M\" is magnetic direction.",
"Indicates the bearing to the destination point. The range of values is from 0.00 to 359.99.",
"Indicates the unit used to express the distance to the destination point. \"K\", \"M\" and \"N\" represent kilometers, miles and knots.",
"Indicates the distance to the destination point.", "A character string recording the name of the method used for location finding. The first byte indicates the character code used, and this is followed by the name of the method.",
"A character string recording the name of the GPS area. The first byte indicates the character code used, and this is followed by the name of the GPS area.",
"A character string recording date and time information relative to UTC (Coordinated Universal Time). The format is \"YYYY:MM:DD.\".",
"Indicates whether differential correction is applied to the GPS receiver."
), rname = c("image_processingsoftware", "image_newsubfiletype",
"image_subfiletype", "image_imagewidth", "image_imagelength",
"image_bitspersample", "image_compression", "image_photometricinterpretation",
"image_thresholding", "image_cellwidth", "image_celllength",
"image_fillorder", "image_documentname", "image_imagedescription",
"image_make", "image_model", "image_stripoffsets", "image_orientation",
"image_samplesperpixel", "image_rowsperstrip", "image_stripbytecounts",
"image_xresolution", "image_yresolution", "image_planarconfiguration",
"image_grayresponseunit", "image_grayresponsecurve", "image_t4options",
"image_t6options", "image_resolutionunit", "image_pagenumber",
"image_transferfunction", "image_software", "image_datetime",
"image_artist", "image_hostcomputer", "image_predictor", "image_whitepoint",
"image_primarychromaticities", "image_colormap", "image_halftonehints",
"image_tilewidth", "image_tilelength", "image_tileoffsets", "image_tilebytecounts",
"image_subifds", "image_inkset", "image_inknames", "image_numberofinks",
"image_dotrange", "image_targetprinter", "image_extrasamples",
"image_sampleformat", "image_sminsamplevalue", "image_smaxsamplevalue",
"image_transferrange", "image_clippath", "image_xclippathunits",
"image_yclippathunits", "image_indexed", "image_jpegtables",
"image_opiproxy", "image_jpegproc", "image_jpeginterchangeformat",
"image_jpeginterchangeformatlength", "image_jpegrestartinterval",
"image_jpeglosslesspredictors", "image_jpegpointtransforms",
"image_jpegqtables", "image_jpegdctables", "image_jpegactables",
"image_ycbcrcoefficients", "image_ycbcrsubsampling", "image_ycbcrpositioning",
"image_referenceblackwhite", "image_xmlpacket", "image_rating",
"image_ratingpercent", "image_imageid", "image_cfarepeatpatterndim",
"image_cfapattern", "image_batterylevel", "image_copyright",
"image_exposuretime", "image_fnumber", "image_iptcnaa", "image_imageresources",
"image_exiftag", "image_intercolorprofile", "image_exposureprogram",
"image_spectralsensitivity", "image_gpstag", "image_isospeedratings",
"image_oecf", "image_interlace", "image_timezoneoffset", "image_selftimermode",
"image_datetimeoriginal", "image_compressedbitsperpixel", "image_shutterspeedvalue",
"image_aperturevalue", "image_brightnessvalue", "image_exposurebiasvalue",
"image_maxaperturevalue", "image_subjectdistance", "image_meteringmode",
"image_lightsource", "image_flash", "image_focallength", "image_flashenergy",
"image_spatialfrequencyresponse", "image_noise", "image_focalplanexresolution",
"image_focalplaneyresolution", "image_focalplaneresolutionunit",
"image_imagenumber", "image_securityclassification", "image_imagehistory",
"image_subjectlocation", "image_exposureindex", "image_tiffepstandardid",
"image_sensingmethod", "image_xptitle", "image_xpcomment", "image_xpauthor",
"image_xpkeywords", "image_xpsubject", "image_printimagematching",
"image_dngversion", "image_dngbackwardversion", "image_uniquecameramodel",
"image_localizedcameramodel", "image_cfaplanecolor", "image_cfalayout",
"image_linearizationtable", "image_blacklevelrepeatdim", "image_blacklevel",
"image_blackleveldeltah", "image_blackleveldeltav", "image_whitelevel",
"image_defaultscale", "image_defaultcroporigin", "image_defaultcropsize",
"image_colormatrix1", "image_colormatrix2", "image_cameracalibration1",
"image_cameracalibration2", "image_reductionmatrix1", "image_reductionmatrix2",
"image_analogbalance", "image_asshotneutral", "image_asshotwhitexy",
"image_baselineexposure", "image_baselinenoise", "image_baselinesharpness",
"image_bayergreensplit", "image_linearresponselimit", "image_cameraserialnumber",
"image_lensinfo", "image_chromablurradius", "image_antialiasstrength",
"image_shadowscale", "image_dngprivatedata", "image_makernotesafety",
"image_calibrationilluminant1", "image_calibrationilluminant2",
"image_bestqualityscale", "image_rawdatauniqueid", "image_originalrawfilename",
"image_originalrawfiledata", "image_activearea", "image_maskedareas",
"image_asshoticcprofile", "image_asshotpreprofilematrix", "image_currenticcprofile",
"image_currentpreprofilematrix", "image_colorimetricreference",
"image_cameracalibrationsignature", "image_profilecalibrationsignature",
"image_asshotprofilename", "image_noisereductionapplied", "image_profilename",
"image_profilehuesatmapdims", "image_profilehuesatmapdata1",
"image_profilehuesatmapdata2", "image_profiletonecurve", "image_profileembedpolicy",
"image_profilecopyright", "image_forwardmatrix1", "image_forwardmatrix2",
"image_previewapplicationname", "image_previewapplicationversion",
"image_previewsettingsname", "image_previewsettingsdigest", "image_previewcolorspace",
"image_previewdatetime", "image_rawimagedigest", "image_originalrawfiledigest",
"image_subtileblocksize", "image_rowinterleavefactor", "image_profilelooktabledims",
"image_profilelooktabledata", "image_opcodelist1", "image_opcodelist2",
"image_opcodelist3", "image_noiseprofile", "photo_exposuretime",
"photo_fnumber", "photo_exposureprogram", "photo_spectralsensitivity",
"photo_isospeedratings", "photo_oecf", "photo_sensitivitytype",
"photo_standardoutputsensitivity", "photo_recommendedexposureindex",
"photo_isospeed", "photo_isospeedlatitudeyyy", "photo_isospeedlatitudezzz",
"photo_exifversion", "photo_datetimeoriginal", "photo_datetimedigitized",
"photo_componentsconfiguration", "photo_compressedbitsperpixel",
"photo_shutterspeedvalue", "photo_aperturevalue", "photo_brightnessvalue",
"photo_exposurebiasvalue", "photo_maxaperturevalue", "photo_subjectdistance",
"photo_meteringmode", "photo_lightsource", "photo_flash", "photo_focallength",
"photo_subjectarea", "photo_makernote", "photo_usercomment",
"photo_subsectime", "photo_subsectimeoriginal", "photo_subsectimedigitized",
"photo_flashpixversion", "photo_colorspace", "photo_pixelxdimension",
"photo_pixelydimension", "photo_relatedsoundfile", "photo_interoperabilitytag",
"photo_flashenergy", "photo_spatialfrequencyresponse", "photo_focalplanexresolution",
"photo_focalplaneyresolution", "photo_focalplaneresolutionunit",
"photo_subjectlocation", "photo_exposureindex", "photo_sensingmethod",
"photo_filesource", "photo_scenetype", "photo_cfapattern", "photo_customrendered",
"photo_exposuremode", "photo_whitebalance", "photo_digitalzoomratio",
"photo_focallengthin35mmfilm", "photo_scenecapturetype", "photo_gaincontrol",
"photo_contrast", "photo_saturation", "photo_sharpness", "photo_devicesettingdescription",
"photo_subjectdistancerange", "photo_imageuniqueid", "photo_cameraownername",
"photo_bodyserialnumber", "photo_lensspecification", "photo_lensmake",
"photo_lensmodel", "photo_lensserialnumber", "iop_interoperabilityindex",
"iop_interoperabilityversion", "iop_relatedimagefileformat",
"iop_relatedimagewidth", "iop_relatedimagelength", "gpsinfo_gpsversionid",
"gpsinfo_gpslatituderef", "gpsinfo_gpslatitude", "gpsinfo_gpslongituderef",
"gpsinfo_gpslongitude", "gpsinfo_gpsaltituderef", "gpsinfo_gpsaltitude",
"gpsinfo_gpstimestamp", "gpsinfo_gpssatellites", "gpsinfo_gpsstatus",
"gpsinfo_gpsmeasuremode", "gpsinfo_gpsdop", "gpsinfo_gpsspeedref",
"gpsinfo_gpsspeed", "gpsinfo_gpstrackref", "gpsinfo_gpstrack",
"gpsinfo_gpsimgdirectionref", "gpsinfo_gpsimgdirection", "gpsinfo_gpsmapdatum",
"gpsinfo_gpsdestlatituderef", "gpsinfo_gpsdestlatitude", "gpsinfo_gpsdestlongituderef",
"gpsinfo_gpsdestlongitude", "gpsinfo_gpsdestbearingref", "gpsinfo_gpsdestbearing",
"gpsinfo_gpsdestdistanceref", "gpsinfo_gpsdestdistance", "gpsinfo_gpsprocessingmethod",
"gpsinfo_gpsareainformation", "gpsinfo_gpsdatestamp", "gpsinfo_gpsdifferential"
)), .Names = c("key", "type", "description", "rname"), class = c("tbl_df",
"tbl", "data.frame"), row.names = c(NA, -310L)) -> .exiv_keys

.exiv_types <-
  c("ascii", "long", "short", "rational", "byte", "sshort",
    "srational", "float", "double", "comment")