# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

int_get_exif <- function(path) {
    .Call('_exiv_int_get_exif', PACKAGE = 'exiv', path)
}

int_set_exif_ascii <- function(path, key, value) {
    invisible(.Call('_exiv_int_set_exif_ascii', PACKAGE = 'exiv', path, key, value))
}

